spring.application.name=the-best-parking
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/estacionamento
spring.datasource.username=postgres
spring.datasource.password=luan123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
